create table lab_inspection_plan (
    id bigint not null auto_increment,
    plan_name varchar(100) not null,
    laboratory_id bigint not null,
    frequency_type varchar(16) not null,
    interval_value int not null,
    execute_time time not null,
    day_of_week tinyint null,
    day_of_month tinyint null,
    next_run_at datetime(3) not null,
    owner_id bigint not null,
    deadline_rule varchar(24) not null,
    deadline_offset_minutes int not null,
    status varchar(16) not null default 'DISABLED',
    version int not null default 0,
    create_by varchar(64) not null default '',
    create_time datetime(3) not null,
    update_by varchar(64) not null default '',
    update_time datetime(3) null,
    del_flag char(1) not null default '0',
    primary key (id),
    constraint fk_inspection_plan_lab foreign key (laboratory_id) references lab_laboratory(id),
    constraint ck_inspection_frequency check (frequency_type in ('DAILY', 'WEEKLY', 'MONTHLY')),
    constraint ck_inspection_interval check (interval_value between 1 and 31),
    constraint ck_inspection_plan_status check (status in ('ENABLED', 'DISABLED')),
    index idx_inspection_plan_due (status, next_run_at)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table lab_inspection_plan_item (
    id bigint not null auto_increment,
    plan_id bigint not null,
    item_code varchar(32) not null,
    content varchar(500) not null,
    sort_order int not null,
    enabled char(1) not null default '1',
    create_time datetime(3) not null,
    update_time datetime(3) null,
    del_flag char(1) not null default '0',
    primary key (id),
    constraint uk_plan_item_code unique (plan_id, item_code),
    constraint fk_plan_item_plan foreign key (plan_id) references lab_inspection_plan(id),
    index idx_plan_item_enabled (plan_id, enabled, sort_order)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table lab_inspection_task (
    id bigint not null auto_increment,
    task_no varchar(32) not null,
    plan_id bigint not null,
    laboratory_id bigint not null,
    scheduled_at datetime(3) not null,
    deadline_at datetime(3) not null,
    assignee_id bigint not null,
    status varchar(20) not null default 'PENDING',
    overdue_flag char(1) not null default '0',
    started_at datetime(3) null,
    completed_at datetime(3) null,
    version int not null default 0,
    create_by varchar(64) not null default '',
    create_time datetime(3) not null,
    update_by varchar(64) not null default '',
    update_time datetime(3) null,
    del_flag char(1) not null default '0',
    primary key (id),
    constraint uk_inspection_task_no unique (task_no),
    constraint uk_inspection_task_schedule unique (plan_id, scheduled_at),
    constraint fk_inspection_task_plan foreign key (plan_id) references lab_inspection_plan(id),
    constraint fk_inspection_task_lab foreign key (laboratory_id) references lab_laboratory(id),
    constraint ck_inspection_task_status check (status in ('PENDING', 'IN_PROGRESS', 'COMPLETED')),
    index idx_inspection_task_assignee (assignee_id, status, deadline_at)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table lab_inspection_item (
    id bigint not null auto_increment,
    task_id bigint not null,
    plan_item_id bigint not null,
    item_code_snapshot varchar(32) not null,
    content_snapshot varchar(500) not null,
    sort_order_snapshot int not null,
    result varchar(16) null,
    description varchar(1000) null,
    severity varchar(16) null,
    target_type varchar(16) null,
    target_id bigint null,
    inspected_by bigint null,
    inspected_at datetime(3) null,
    version int not null default 0,
    create_time datetime(3) not null,
    update_time datetime(3) null,
    del_flag char(1) not null default '0',
    primary key (id),
    constraint uk_task_plan_item unique (task_id, plan_item_id),
    constraint fk_inspection_item_task foreign key (task_id) references lab_inspection_task(id),
    constraint fk_inspection_item_plan_item foreign key (plan_item_id) references lab_inspection_plan_item(id),
    constraint ck_inspection_result check (result is null or result in ('PASS', 'FAIL', 'NOT_APPLICABLE')),
    constraint ck_inspection_severity check (severity is null or severity in ('LOW', 'MEDIUM', 'HIGH', 'MAJOR')),
    index idx_inspection_item_task_sort (task_id, sort_order_snapshot)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table lab_hazard (
    id bigint not null auto_increment,
    hazard_no varchar(32) not null,
    source_item_id bigint null,
    related_hazard_id bigint null,
    target_type varchar(16) not null,
    target_id bigint not null,
    severity varchar(16) not null,
    owner_id bigint not null,
    deadline datetime(3) not null,
    requirements varchar(2000) not null,
    status varchar(32) not null default 'PENDING_RECTIFICATION',
    overdue_flag char(1) not null default '0',
    version int not null default 0,
    create_by varchar(64) not null default '',
    create_time datetime(3) not null,
    update_by varchar(64) not null default '',
    update_time datetime(3) null,
    del_flag char(1) not null default '0',
    primary key (id),
    constraint uk_hazard_no unique (hazard_no),
    constraint uk_hazard_source_item unique (source_item_id),
    constraint fk_hazard_source_item foreign key (source_item_id) references lab_inspection_item(id),
    constraint fk_hazard_related foreign key (related_hazard_id) references lab_hazard(id),
    constraint ck_hazard_target check (target_type in ('LABORATORY', 'DEVICE')),
    constraint ck_hazard_severity check (severity in ('LOW', 'MEDIUM', 'HIGH', 'MAJOR')),
    constraint ck_hazard_status check (
        status in ('PENDING_RECTIFICATION', 'RECTIFYING', 'PENDING_REVIEW', 'CLOSED')
    ),
    index idx_hazard_blocker (target_type, target_id, severity, status),
    index idx_hazard_owner_due (owner_id, status, deadline)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table lab_rectification (
    id bigint not null auto_increment,
    hazard_id bigint not null,
    round_no int not null,
    submitter_id bigint not null,
    description varchar(2000) not null,
    submitted_at datetime(3) not null,
    reviewer_id bigint null,
    review_result varchar(16) null,
    review_reason varchar(1000) null,
    reviewed_at datetime(3) null,
    create_time datetime(3) not null,
    update_time datetime(3) null,
    version int not null default 0,
    del_flag char(1) not null default '0',
    primary key (id),
    constraint uk_rectification_round unique (hazard_id, round_no),
    constraint fk_rectification_hazard foreign key (hazard_id) references lab_hazard(id),
    constraint ck_rectification_round check (round_no > 0),
    constraint ck_rectification_review check (
        review_result is null or review_result in ('PASSED', 'REJECTED')
    ),
    index idx_rectification_hazard_time (hazard_id, submitted_at)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci;
